-- 선명 테스트 주문 2건(95,97) 하드삭제 — orders/core.ts DELETE cascade 미러 (CANCELLED 상태 확인됨)
DELETE FROM card_status_history WHERE card_id IN (SELECT id FROM cards WHERE order_id IN (95,97));
DELETE FROM quality_issues WHERE card_id IN (SELECT id FROM cards WHERE order_id IN (95,97));
DELETE FROM waste_records WHERE card_id IN (SELECT id FROM cards WHERE order_id IN (95,97));
UPDATE print_events SET card_id = NULL WHERE card_id IN (SELECT id FROM cards WHERE order_id IN (95,97));
DELETE FROM card_items WHERE card_id IN (SELECT id FROM cards WHERE order_id IN (95,97));
UPDATE tasks SET card_id = NULL WHERE card_id IN (SELECT id FROM cards WHERE order_id IN (95,97));
DELETE FROM work_records WHERE card_id IN (SELECT id FROM cards WHERE order_id IN (95,97));
UPDATE print_file_map SET card_id = NULL WHERE card_id IN (SELECT id FROM cards WHERE order_id IN (95,97));
DELETE FROM inventory_auto_deductions WHERE card_id IN (SELECT id FROM cards WHERE order_id IN (95,97));
UPDATE quality_issues SET rework_card_id = NULL WHERE rework_card_id IN (SELECT id FROM cards WHERE order_id IN (95,97));
DELETE FROM customer_claims WHERE order_id IN (95,97);
DELETE FROM returns WHERE order_id IN (95,97);
DELETE FROM credit_overrides WHERE order_id IN (95,97);
DELETE FROM shipment_items WHERE shipment_id IN (SELECT id FROM shipments WHERE order_id IN (95,97));
UPDATE shipments SET merged_into_id = NULL WHERE merged_into_id IN (SELECT id FROM shipments WHERE order_id IN (95,97));
DELETE FROM shipments WHERE order_id IN (95,97);
DELETE FROM cards WHERE order_id IN (95,97);
UPDATE print_file_map SET order_item_id = NULL WHERE order_item_id IN (SELECT id FROM order_items WHERE order_id IN (95,97));
DELETE FROM return_items WHERE order_item_id IN (SELECT id FROM order_items WHERE order_id IN (95,97));
DELETE FROM pp_material_deductions WHERE order_id IN (95,97);
DELETE FROM original_archives WHERE order_id IN (95,97);
DELETE FROM order_items WHERE order_id IN (95,97);
DELETE FROM order_billing_groups WHERE order_id IN (95,97);
DELETE FROM order_status_history WHERE order_id IN (95,97);
DELETE FROM tax_invoice_orders WHERE order_id IN (95,97);
DELETE FROM order_ai_files WHERE order_id IN (95,97);
DELETE FROM auto_process_jobs WHERE order_id IN (95,97);
UPDATE tasks SET order_id = NULL WHERE order_id IN (95,97);
UPDATE customer_claims SET rework_order_id = NULL WHERE rework_order_id IN (95,97);
UPDATE portal_reorder_requests SET reference_order_id = NULL WHERE reference_order_id IN (95,97);
UPDATE cash_receipts SET order_id = NULL WHERE order_id IN (95,97);
UPDATE tax_invoices SET order_id = NULL WHERE order_id IN (95,97) AND status = 'CANCELLED';
DELETE FROM orders WHERE id IN (95,97);
