-- A1 공급사/변형 매칭
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='KEL-IT-127'), updated_at=CURRENT_TIMESTAMP WHERE item_name='PVC(켈)(30m)-잉크테크 [127폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SYN-NA-127'), updated_at=CURRENT_TIMESTAMP WHERE item_name='비점착합성지(30m)-호홍 [127폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SVB-040'), updated_at=CURRENT_TIMESTAMP WHERE item_name='솔벤 현수막-TPM [40폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SVB-PR-152'), updated_at=CURRENT_TIMESTAMP WHERE item_name='솔벤 현수막-TPM(S150 고급형) [152폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SVB-PR-152'), updated_at=CURRENT_TIMESTAMP WHERE item_name='솔벤 현수막-TPM(고급형) [152폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SV-PATB-NAT'), updated_at=CURRENT_TIMESTAMP WHERE item_name='솔벤패트배너-나투라 [127폭/30m]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SV-PATB-NAT'), updated_at=CURRENT_TIMESTAMP WHERE item_name='솔벤패트배너-나투라(6롤중 2롤은 635cm로 재단부탁드립니다.) [127폭/30m]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='PAT-IT-127'), updated_at=CURRENT_TIMESTAMP WHERE item_name='패트배너(30m)-잉크테크 [127폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='PAT-IT-152'), updated_at=CURRENT_TIMESTAMP WHERE item_name='패트배너(30m)-잉크테크 [152폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
