-- 일괄8: 족자봉/캡바적색/투광기/원형돌출/로프
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-038'), updated_at=CURRENT_TIMESTAMP WHERE item_name='3.5mm재단로프 [1마대800개/총200m]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-037-5MM'), updated_at=CURRENT_TIMESTAMP WHERE item_name='5mm볼로프' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-LEDP-WW'), updated_at=CURRENT_TIMESTAMP WHERE item_name='LED투광기-백색/백색 [35W]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-LEDP-WM'), updated_at=CURRENT_TIMESTAMP WHERE item_name='LED투광기-백색/웜 [35W]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-049-SQ'), updated_at=CURRENT_TIMESTAMP WHERE item_name='사각족자봉' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-049-SQ'), updated_at=CURRENT_TIMESTAMP WHERE item_name='사각족자봉 [3m]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-049-SQ'), updated_at=CURRENT_TIMESTAMP WHERE item_name='사각족자봉 [94cm]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-SRND-D500'), updated_at=CURRENT_TIMESTAMP WHERE item_name='스텐원형돌출 [500Φ]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-SRND-D600'), updated_at=CURRENT_TIMESTAMP WHERE item_name='스텐원형돌출 [600Φ]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-049-CR'), updated_at=CURRENT_TIMESTAMP WHERE item_name='원형족자봉 [16Ø]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-049-CR'), updated_at=CURRENT_TIMESTAMP WHERE item_name='원형족자봉 [21Ø]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-049-CR'), updated_at=CURRENT_TIMESTAMP WHERE item_name='원형족자봉(고리가 안들어가요 교환해주세요) [21Ø]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-KPB-RD'), updated_at=CURRENT_TIMESTAMP WHERE item_name='채널용 캡바 [적색/25mm*3m]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-PRND-D500'), updated_at=CURRENT_TIMESTAMP WHERE item_name='포인트원형돌출 [500Φ]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-PRND-D600'), updated_at=CURRENT_TIMESTAMP WHERE item_name='포인트원형돌출 [600Φ]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
