-- 일괄3 확실: LED규격/아일렛/E26T유광/하바카바검정/LD59
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='JG-E26T-P127'), updated_at=CURRENT_TIMESTAMP WHERE item_name='E26T 유광(45m/200g) [127폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='LD59HTG-137'), updated_at=CURRENT_TIMESTAMP WHERE item_name='LD59THG [137폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-LEDF-F20S'), updated_at=CURRENT_TIMESTAMP WHERE item_name='LED형광등 [20w-단면]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-LEDF-F20W'), updated_at=CURRENT_TIMESTAMP WHERE item_name='LED형광등 [20w-웜(전구색)]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-LEDF-F28D60'), updated_at=CURRENT_TIMESTAMP WHERE item_name='LED형광등 [28w-양면(60cm)]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-LEDF-F28D'), updated_at=CURRENT_TIMESTAMP WHERE item_name='LED형광등 [28w-양면(돌출)]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-045-24-S'), updated_at=CURRENT_TIMESTAMP WHERE item_name='아일렛(하도매) 1마대 [24호/은색]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-045-24-G'), updated_at=CURRENT_TIMESTAMP WHERE item_name='아일렛(하도매) [24호/금색]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-045-24-S'), updated_at=CURRENT_TIMESTAMP WHERE item_name='아일렛(하도매) [24호/은색]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-045-5-S'), updated_at=CURRENT_TIMESTAMP WHERE item_name='아일렛(하도매) [5호/은색]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-045-9-S'), updated_at=CURRENT_TIMESTAMP WHERE item_name='아일렛(하도매) [9호/은색]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-CB-BK'), updated_at=CURRENT_TIMESTAMP WHERE item_name='카바 [검정]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-HB-BK'), updated_at=CURRENT_TIMESTAMP WHERE item_name='하바 [검정]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
