-- 일괄15 매칭: 배너거치대6/인두기 + 실내일자형
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-011'), updated_at=CURRENT_TIMESTAMP WHERE item_name='실외배너 물통SET(복배너) [60*180]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-017'), updated_at=CURRENT_TIMESTAMP WHERE item_name='윈드배너 물통형-SET(소) [76*180]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-026'), updated_at=CURRENT_TIMESTAMP WHERE item_name='실외용 철제배너-TSO(브랏켓형) [60*180]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-028'), updated_at=CURRENT_TIMESTAMP WHERE item_name='실내용 철제배너-TS [50*150]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-025'), updated_at=CURRENT_TIMESTAMP WHERE item_name='빅폴 SET [150*140~240]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-023'), updated_at=CURRENT_TIMESTAMP WHERE item_name='자이언트 폴SET(대) [6m/120*400]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='GDS-INDUGI'), updated_at=CURRENT_TIMESTAMP WHERE item_name='인두기(열재단) [나무손잡이]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-BN-STR'), updated_at=CURRENT_TIMESTAMP WHERE item_name='실내배너 일자형(W) [60*180]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
