-- 일괄5 확실: 트러스바/LED3구/타카핀/하바카바백색/무광일반엠보
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-LED3-WH'), updated_at=CURRENT_TIMESTAMP WHERE item_name='LED 3구(백색) [1w]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='HJ-MGILBO-P127'), updated_at=CURRENT_TIMESTAMP WHERE item_name='무광코팅지 일반엠보(45m/180g) [127폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='HJ-MGILBO-P60'), updated_at=CURRENT_TIMESTAMP WHERE item_name='무광코팅지 일반엠보(45m/180g) [60폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='HJ-MGILBO-P90'), updated_at=CURRENT_TIMESTAMP WHERE item_name='무광코팅지 일반엠보(45m/180g) [90폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-CB-WH'), updated_at=CURRENT_TIMESTAMP WHERE item_name='카바' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-TACK-T4'), updated_at=CURRENT_TIMESTAMP WHERE item_name='타카핀 [4mm]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-TACK-T6'), updated_at=CURRENT_TIMESTAMP WHERE item_name='타카핀 [6mm]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-TRB-R150-LG'), updated_at=CURRENT_TIMESTAMP WHERE item_name='트러스바 [150mm*7m/연회색]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-TRB-R200-WH'), updated_at=CURRENT_TIMESTAMP WHERE item_name='트러스바 [200mm*7m/백색]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-TRB-R300-BK'), updated_at=CURRENT_TIMESTAMP WHERE item_name='트러스바 [300mm*7m/검정]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-TRB-R300-LG'), updated_at=CURRENT_TIMESTAMP WHERE item_name='트러스바 [300mm*7m/연회색]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-TRB-R400-BK'), updated_at=CURRENT_TIMESTAMP WHERE item_name='트러스바 [400mm*7m/검정]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-TRB-R200-WH'), updated_at=CURRENT_TIMESTAMP WHERE item_name='트러스바 옆마구리 [200mm*113mm/백색]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-HB-WH'), updated_at=CURRENT_TIMESTAMP WHERE item_name='하바' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
