-- 일괄7: 후렉스/백릿/캠퍼스/폼보드/고무자석/도안지/인화지/발통/파이프/실리콘/시트150->152
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-PIPE-P15'), updated_at=CURRENT_TIMESTAMP WHERE item_name='15각 파이프' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-PIPE-P19'), updated_at=CURRENT_TIMESTAMP WHERE item_name='19각 파이프' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SPM011G-152'), updated_at=CURRENT_TIMESTAMP WHERE item_name='SPM011G [150폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SPP031M-152'), updated_at=CURRENT_TIMESTAMP WHERE item_name='SPP031M [150폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='MAG-060'), updated_at=CURRENT_TIMESTAMP WHERE item_name='고무자석시트-일반(0.8T) [60폭/10m]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='MAG-100'), updated_at=CURRENT_TIMESTAMP WHERE item_name='고무자석시트-차량용(0.8T) [100폭/10m]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-DOAN'), updated_at=CURRENT_TIMESTAMP WHERE item_name='도안지 [125폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='PJ-MUINH'), updated_at=CURRENT_TIMESTAMP WHERE item_name='무광인화지 [127폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-FOOT-F500'), updated_at=CURRENT_TIMESTAMP WHERE item_name='발통 [500mm]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-FOOT-F400'), updated_at=CURRENT_TIMESTAMP WHERE item_name='발통-400 [1box=6ea]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-FOOT-F700'), updated_at=CURRENT_TIMESTAMP WHERE item_name='발통-700 [1box=5ea]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='FLEXN-100'), updated_at=CURRENT_TIMESTAMP WHERE item_name='비조명후렉스 [100]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SVCV-127'), updated_at=CURRENT_TIMESTAMP WHERE item_name='솔벤 캠퍼스 [127폭/20m]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='PJ-BACKLIT-P127'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성 백릿-프라임 [127폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-SIL'), updated_at=CURRENT_TIMESTAMP WHERE item_name='실리콘 [백색]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-SIL'), updated_at=CURRENT_TIMESTAMP WHERE item_name='실리콘 [투명]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='FOM-5T-W-48'), updated_at=CURRENT_TIMESTAMP WHERE item_name='폼보드 [4*8(5T)]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
