-- 일괄9: LED전선/보강대/지지대/쌍클립/피스/큐방/삼각고리/상코너/E4엠보/손기계
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='JG-E4-P127'), updated_at=CURRENT_TIMESTAMP WHERE item_name='E4 엠보 무광(45m/200g) [127폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='JG-E4-P152'), updated_at=CURRENT_TIMESTAMP WHERE item_name='E4 엠보 무광(45m/200g) [152폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='JG-E4-P60'), updated_at=CURRENT_TIMESTAMP WHERE item_name='E4 엠보 무광(45m/200g) [60폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='JG-E4-P90'), updated_at=CURRENT_TIMESTAMP WHERE item_name='E4 엠보 무광(45m/200g) [90폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-LEDW'), updated_at=CURRENT_TIMESTAMP WHERE item_name='LED 2P 전선 [100m]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-SC'), updated_at=CURRENT_TIMESTAMP WHERE item_name='상코너' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-048'), updated_at=CURRENT_TIMESTAMP WHERE item_name='쌍클립' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-SCREW'), updated_at=CURRENT_TIMESTAMP WHERE item_name='직결피스 [1box-12000ea]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-CRF'), updated_at=CURRENT_TIMESTAMP WHERE item_name='채널 보강대' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-CSP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='채널 지지대' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-CSP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='채널 지지대 [72mm]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-047-OT'), updated_at=CURRENT_TIMESTAMP WHERE item_name='큐방-원터치 [40￠/1봉(250개)]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-TRF'), updated_at=CURRENT_TIMESTAMP WHERE item_name='트러스바 보강대 [200mm]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-050-P12'), updated_at=CURRENT_TIMESTAMP WHERE item_name='판형 삼각접착고리 [12Ø]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-050-NP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='판형 삼각접착고리 [무펀치]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='GDS-HDMGI'), updated_at=CURRENT_TIMESTAMP WHERE item_name='하도매 기계(손기계) [수동]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
