-- 일괄2 확실: 부직포/양면코팅/채널바(색)/텐트천
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='BUJIK-180'), updated_at=CURRENT_TIMESTAMP WHERE item_name='부직포 [180폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='BUJIK-127'), updated_at=CURRENT_TIMESTAMP WHERE item_name='부직포-S [127폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='BUJIK-060'), updated_at=CURRENT_TIMESTAMP WHERE item_name='부직포-S [60폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='BUJIK-090'), updated_at=CURRENT_TIMESTAMP WHERE item_name='부직포-S [90폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SV-TENT'), updated_at=CURRENT_TIMESTAMP WHERE item_name='솔벤 텐트천(300D) [200폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SV-TENT'), updated_at=CURRENT_TIMESTAMP WHERE item_name='솔벤 텐트천(300D) [250폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SV-TENT'), updated_at=CURRENT_TIMESTAMP WHERE item_name='솔벤 텐트천(300D) [320폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='JG-A26-P127'), updated_at=CURRENT_TIMESTAMP WHERE item_name='양면코팅지(30m) [127폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='JG-A26-P127'), updated_at=CURRENT_TIMESTAMP WHERE item_name='양면코팅지(50m) [127폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-IPB-WH'), updated_at=CURRENT_TIMESTAMP WHERE item_name='채널용 입체바 [백색/100mm*3m]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-IPB-WH'), updated_at=CURRENT_TIMESTAMP WHERE item_name='채널용 입체바 [백색/80mm*3m]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-IPB-BK'), updated_at=CURRENT_TIMESTAMP WHERE item_name='채널용 입체바 [흑색/80mm*3m]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-KPB-WH'), updated_at=CURRENT_TIMESTAMP WHERE item_name='채널용 캡바 [백색/25mm*3m]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-KPB-BK'), updated_at=CURRENT_TIMESTAMP WHERE item_name='채널용 캡바 [흑색/25mm*3m]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
