-- 일괄 확실분: 무광자동호홍(MCP)+상바(SGM-SB)+SMPS(W규격)
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='MCP120-090'), updated_at=CURRENT_TIMESTAMP WHERE item_name='무광 코팅지 자동용(45m/120g)-호홍 [90폭(교환)]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='MCP120-090'), updated_at=CURRENT_TIMESTAMP WHERE item_name='무광 코팅지 자동용(45m/120g)-호홍 [90폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='MCP180-127'), updated_at=CURRENT_TIMESTAMP WHERE item_name='무광 코팅지 자동용(45m/180g)-호홍 [127폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='MCP180-090'), updated_at=CURRENT_TIMESTAMP WHERE item_name='무광 코팅지 자동용(45m/180g)-호홍 [90폭(반품)]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='MCP180-090'), updated_at=CURRENT_TIMESTAMP WHERE item_name='무광 코팅지 자동용(45m/180g)-호홍 [90폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='MCP120-127'), updated_at=CURRENT_TIMESTAMP WHERE item_name='무광 코팅지 자동용(61m/120g)-호홍 [127폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='MCP120-060'), updated_at=CURRENT_TIMESTAMP WHERE item_name='무광 코팅지 자동용(61m/120g)-호홍 [60폭]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-SB'), updated_at=CURRENT_TIMESTAMP WHERE item_name='상바' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-SMPS-W200'), updated_at=CURRENT_TIMESTAMP WHERE item_name='외부용 SMPS(방수) [200wt]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-SMPS-W300'), updated_at=CURRENT_TIMESTAMP WHERE item_name='외부용 SMPS(방수) [300wt]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-SMPS-W400'), updated_at=CURRENT_TIMESTAMP WHERE item_name='외부용 SMPS(방수) [400wt]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='SGM-SMPS-W500'), updated_at=CURRENT_TIMESTAMP WHERE item_name='외부용 SMPS(방수) [500wt]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
