-- 잉크-2 개별포장 매칭
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I0001-ITP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 C(ITP-개별포장)' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I0001-ITP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 C(개별박스)' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I0001-ITP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 C(개별포장)' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I0004-ITP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 K(ITP-개별포장)' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I0004-ITP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 K(개별포장)' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I0005-ITP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 LC(ITP-개별포장)' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I0005-ITP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 LC(개별포장)' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I0006-ITP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 LM(ITP-개별포장)' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I0006-ITP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 LM(개별박스)' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I0006-ITP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 LM(개별포장)' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I0002-ITP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 M(ITP-개별포장)' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I0002-ITP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 M(개별박스)' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I0002-ITP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 M(개별포장)' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I0003-ITP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 Y(ITP-개별포장)' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I0003-ITP'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 Y(개별포장)' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
