-- TPM잉크 매칭
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I-TPM-C-20L'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 C [20L]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I-TPM-C-5L'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 C [5L]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I-TPM-C-5L'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 C [5리터]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I-TPM-K-20L'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 K [20L]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I-TPM-K-5L'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 K [5L]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I-TPM-K-5L'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 K [5리터]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I-TPM-M-20L'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 M [20L]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I-TPM-M-5L'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 M [5L]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I-TPM-M-5L'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 M [5리터]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I-TPM-Y-20L'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 Y [20L]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I-TPM-Y-5L'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 Y [5L]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='RM-I-TPM-Y-5L'), updated_at=CURRENT_TIMESTAMP WHERE item_name='수성잉크 Y [5리터]' AND item_id IS NULL AND po_id IN (SELECT id FROM purchase_orders WHERE entity_id=2 AND notes='선명 이관 매입');
