-- ============================================================================
-- Migration 0258: 전사 품목 재등록 (category_id NOT NULL 누락 수정)
-- category_id = (SELECT id FROM item_categories WHERE category_name='전사')
-- ============================================================================

INSERT OR IGNORE INTO items (
  category_id, item_code, item_name, category, sub_category, item_type, unit,
  base_price, pricing_method, print_method_id, print_media_id,
  is_sales_item, is_purchase_item, is_active
) VALUES
-- 윈드배너 (매쉬)
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-101', '윈드배너', '전사', '윈드배너', 'PRODUCT', 'EA',
   13000, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='MESH'),
   1, 0, 1),
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-102', '윈드배너(대)', '전사', '윈드배너', 'PRODUCT', 'EA',
   18000, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='MESH'),
   1, 0, 1),

-- 가로등배너 (폰지)
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-201', '가로등배너', '전사', '가로등배너', 'PRODUCT', 'EA',
   0, 'AREA',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='PONGE'),
   1, 0, 1),
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-202', '가로등배너(대형)', '전사', '가로등배너', 'PRODUCT', 'EA',
   0, 'AREA',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='PONGE'),
   1, 0, 1),

-- 정기 (폰지/사틴)
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-301', '정기(폰지)', '전사', '정기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='PONGE'),
   1, 0, 1),
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-302', '정기(사틴)', '전사', '정기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='SATIN'),
   1, 0, 1),
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-303', '정기자수', '전사', '정기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='PONGE'),
   1, 0, 1),

-- 군기 (폰지/사틴)
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-401', '군기(폰지)', '전사', '군기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='PONGE'),
   1, 0, 1),
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-402', '군기(사틴)', '전사', '군기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='SATIN'),
   1, 0, 1),

-- 탁상기 (사틴/폰지)
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-501', '탁상기(사틴)', '전사', '탁상기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='SATIN'),
   1, 0, 1),
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-502', '탁상기(폰지)', '전사', '탁상기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='PONGE'),
   1, 0, 1),

-- 근조기 (외주)
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-601', '근조기(외주)', '전사', '근조기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   NULL,
   1, 0, 1),

-- 워킹배너 (매쉬)
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-701', '워킹배너', '전사', '워킹배너', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='MESH'),
   1, 0, 1),

-- 자이언트배너 (매쉬)
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-801', '자이언트배너', '전사', '자이언트배너', 'PRODUCT', 'EA',
   0, 'AREA',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='MESH'),
   1, 0, 1),

-- 수기 (폰지)
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-901', '수기', '전사', '수기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='PONGE'),
   1, 0, 1),
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-902', '수기태극기', '전사', '수기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='PONGE'),
   1, 0, 1),

-- 태극기 (사틴, 규격별)
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-011', '태극기 1호(150×100)', '전사', '정기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='SATIN'),
   1, 0, 1),
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-012', '태극기 2호(135×90)', '전사', '정기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='SATIN'),
   1, 0, 1),
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-013', '태극기 3호(120×80)', '전사', '정기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='SATIN'),
   1, 0, 1),
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-014', '태극기 4호(95×60)', '전사', '정기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='SATIN'),
   1, 0, 1),
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-015', '태극기 5호(70×45)', '전사', '정기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='SATIN'),
   1, 0, 1),
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-016', '태극기 6호(50×35)', '전사', '정기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='SATIN'),
   1, 0, 1),
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-017', '태극기 특호(200×135)', '전사', '정기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='SATIN'),
   1, 0, 1),
  ((SELECT id FROM item_categories WHERE category_name='전사'),
   'TF-018', '태극기 탁상용(30×20)', '전사', '탁상기', 'PRODUCT', 'EA',
   0, 'FIXED',
   (SELECT id FROM print_methods WHERE code='TRANSFER'),
   (SELECT id FROM print_media WHERE code='SATIN'),
   1, 0, 1);
