-- 0428_split_multisize_variants.sql
-- 복수 규격이 한 품목에 묶인 것을 규격별 변종으로 분리 (사용자 요청).
-- 대상: 정기 자수/본염·태극기 정기자수(135×90·120×80)·근조기 자수(80×115·110×75)·좌우보필형 액자(3규격).
-- 방식: 기존 품목=base 템플릿(spec_group 지정·spec_value NULL·is_active=0), 규격별 변종 신규(is_active=1, base 필드 상속).

INSERT INTO spec_groups (name,unit,sort_order,is_active) SELECT '깃발규격','규격',80,1 WHERE NOT EXISTS (SELECT 1 FROM spec_groups WHERE name='깃발규격');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='깃발규격'),'S135X90','135×90',10,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='깃발규격') AND value_code='S135X90');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='깃발규격'),'S120X80','120×80',20,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='깃발규격') AND value_code='S120X80');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='깃발규격'),'S80X115','80×115',30,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='깃발규격') AND value_code='S80X115');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='깃발규격'),'S110X75','110×75',40,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='깃발규격') AND value_code='S110X75');
INSERT INTO spec_groups (name,unit,sort_order,is_active) SELECT '액자규격','규격',80,1 WHERE NOT EXISTS (SELECT 1 FROM spec_groups WHERE name='액자규격');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='액자규격'),'S30X45','30×45',10,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='액자규격') AND value_code='S30X45');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='액자규격'),'S60X40','60×40',20,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='액자규격') AND value_code='S60X40');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='액자규격'),'S20X30','20×30',30,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='액자규격') AND value_code='S20X30');

-- ■ JG-JASU → 깃발규격 변종 2
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'JG-JASU-S135X90', item_name||' 135×90', 1, (SELECT id FROM spec_groups WHERE name='깃발규격'), 'S135X90', '135×90', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='JG-JASU' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='JG-JASU-S135X90');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'JG-JASU-S120X80', item_name||' 120×80', 1, (SELECT id FROM spec_groups WHERE name='깃발규격'), 'S120X80', '120×80', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='JG-JASU' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='JG-JASU-S120X80');
UPDATE items SET spec_group_id=(SELECT id FROM spec_groups WHERE name='깃발규격'), spec_value=NULL, is_active=0, item_group=item_name, specification=NULL, updated_at=datetime('now') WHERE item_code='JG-JASU';

-- ■ JG-BONYEOM → 깃발규격 변종 2
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'JG-BONYEOM-S135X90', item_name||' 135×90', 1, (SELECT id FROM spec_groups WHERE name='깃발규격'), 'S135X90', '135×90', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='JG-BONYEOM' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='JG-BONYEOM-S135X90');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'JG-BONYEOM-S120X80', item_name||' 120×80', 1, (SELECT id FROM spec_groups WHERE name='깃발규격'), 'S120X80', '120×80', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='JG-BONYEOM' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='JG-BONYEOM-S120X80');
UPDATE items SET spec_group_id=(SELECT id FROM spec_groups WHERE name='깃발규격'), spec_value=NULL, is_active=0, item_group=item_name, specification=NULL, updated_at=datetime('now') WHERE item_code='JG-BONYEOM';

-- ■ TGK-JASU → 깃발규격 변종 2
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'TGK-JASU-S135X90', item_name||' 135×90', 1, (SELECT id FROM spec_groups WHERE name='깃발규격'), 'S135X90', '135×90', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='TGK-JASU' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='TGK-JASU-S135X90');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'TGK-JASU-S120X80', item_name||' 120×80', 1, (SELECT id FROM spec_groups WHERE name='깃발규격'), 'S120X80', '120×80', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='TGK-JASU' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='TGK-JASU-S120X80');
UPDATE items SET spec_group_id=(SELECT id FROM spec_groups WHERE name='깃발규격'), spec_value=NULL, is_active=0, item_group=item_name, specification=NULL, updated_at=datetime('now') WHERE item_code='TGK-JASU';

-- ■ GJG-JASU → 깃발규격 변종 2
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'GJG-JASU-S80X115', item_name||' 80×115', 1, (SELECT id FROM spec_groups WHERE name='깃발규격'), 'S80X115', '80×115', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='GJG-JASU' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='GJG-JASU-S80X115');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'GJG-JASU-S110X75', item_name||' 110×75', 1, (SELECT id FROM spec_groups WHERE name='깃발규격'), 'S110X75', '110×75', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='GJG-JASU' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='GJG-JASU-S110X75');
UPDATE items SET spec_group_id=(SELECT id FROM spec_groups WHERE name='깃발규격'), spec_value=NULL, is_active=0, item_group=item_name, specification=NULL, updated_at=datetime('now') WHERE item_code='GJG-JASU';

-- ■ GDS-LRF → 액자규격 변종 3
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'GDS-LRF-S30X45', item_name||' 30×45', 1, (SELECT id FROM spec_groups WHERE name='액자규격'), 'S30X45', '30×45', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='GDS-LRF' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='GDS-LRF-S30X45');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'GDS-LRF-S60X40', item_name||' 60×40', 1, (SELECT id FROM spec_groups WHERE name='액자규격'), 'S60X40', '60×40', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='GDS-LRF' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='GDS-LRF-S60X40');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'GDS-LRF-S20X30', item_name||' 20×30', 1, (SELECT id FROM spec_groups WHERE name='액자규격'), 'S20X30', '20×30', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='GDS-LRF' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='GDS-LRF-S20X30');
UPDATE items SET spec_group_id=(SELECT id FROM spec_groups WHERE name='액자규격'), spec_value=NULL, is_active=0, item_group=item_name, specification=NULL, updated_at=datetime('now') WHERE item_code='GDS-LRF';
