-- 0429_split_accessory_combos.sql
-- 부속품(ACC) 다속성(규격·구수·색·타입) 묶임 → 조합별 개별 품목 분리 (사용자 '전부 나눠줘').
-- 플랫 방식: item_group=원품목명 묶음, item_name=조합 서술(주문 검색/목록 구분). base 필드 상속. 기존 base=is_active=0(숨김).
-- 까치발/족자봉의 규격범위(150~2000mm·85~150cm)는 이산값 부재로 색/타입만 분리, 규격은 spec 유지.
-- (P단 깃대 ACC-032=P-3단·가정용 단일조합이라 분리 대상 아님)

-- ■ ACC-030 → 4
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-030-R130-2', item_name||' R130 2구', 1, 'R130·2구', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-030' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-030-R130-2');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-030-R130-3', item_name||' R130 3구', 1, 'R130·3구', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-030' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-030-R130-3');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-030-R150-2', item_name||' R150 2구', 1, 'R150·2구', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-030' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-030-R150-2');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-030-R150-3', item_name||' R150 3구', 1, 'R150·3구', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-030' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-030-R150-3');
UPDATE items SET is_active=0, item_group=item_name, updated_at=datetime('now') WHERE item_code='ACC-030';

-- ■ ACC-035 → 6
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-035-P-1', item_name||' P형 1구', 1, 'P·1구', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-035' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-035-P-1');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-035-P-2', item_name||' P형 2구', 1, 'P·2구', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-035' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-035-P-2');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-035-S-1', item_name||' S형 1구', 1, 'S·1구', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-035' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-035-S-1');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-035-S-2', item_name||' S형 2구', 1, 'S·2구', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-035' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-035-S-2');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-035-R-1', item_name||' R형 1구', 1, 'R·1구', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-035' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-035-R-1');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-035-R-2', item_name||' R형 2구', 1, 'R·2구', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-035' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-035-R-2');
UPDATE items SET is_active=0, item_group=item_name, updated_at=datetime('now') WHERE item_code='ACC-035';

-- ■ ACC-045 → 6
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-045-5-S', item_name||' 5호 은', 1, '5호·은', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-045' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-045-5-S');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-045-5-G', item_name||' 5호 금', 1, '5호·금', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-045' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-045-5-G');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-045-9-S', item_name||' 9호 은', 1, '9호·은', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-045' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-045-9-S');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-045-9-G', item_name||' 9호 금', 1, '9호·금', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-045' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-045-9-G');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-045-24-S', item_name||' 24호 은', 1, '24호·은', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-045' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-045-24-S');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-045-24-G', item_name||' 24호 금', 1, '24호·금', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-045' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-045-24-G');
UPDATE items SET is_active=0, item_group=item_name, updated_at=datetime('now') WHERE item_code='ACC-045';

-- ■ ACC-047 → 2
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-047-OT', item_name||' 원터치 40파이', 1, '원터치·40파이', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-047' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-047-OT');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-047-AP', item_name||' 압축 40파이', 1, '압축·40파이', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-047' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-047-AP');
UPDATE items SET is_active=0, item_group=item_name, updated_at=datetime('now') WHERE item_code='ACC-047';

-- ■ ACC-050 → 2
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-050-NP', item_name||' 판형 무펀치', 1, '판형·무펀치', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-050' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-050-NP');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-050-P12', item_name||' 판형 12파이', 1, '판형·12파이', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-050' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-050-P12');
UPDATE items SET is_active=0, item_group=item_name, updated_at=datetime('now') WHERE item_code='ACC-050';

-- ■ ACC-049 → 2
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-049-SQ', item_name||' 사각 85~150cm', 1, '사각·85~150cm', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-049' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-049-SQ');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-049-CR', item_name||' 원형 85~150cm', 1, '원형·85~150cm', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-049' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-049-CR');
UPDATE items SET is_active=0, item_group=item_name, updated_at=datetime('now') WHERE item_code='ACC-049';

-- ■ ACC-029 → 3
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-029-BK', item_name||' 흑색', 1, '흑·150~2000mm', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-BK');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-029-WH', item_name||' 백색', 1, '백·150~2000mm', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-WH');
INSERT INTO items (item_code,item_name,is_active,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value,created_at,updated_at)
SELECT 'ACC-029-PT', item_name||' 도색', 1, '도색·150~2000mm', item_name, item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,spec_group_id,spec_value, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-PT');
UPDATE items SET is_active=0, item_group=item_name, updated_at=datetime('now') WHERE item_code='ACC-029';

