-- 0471: 까치발(ACC-029) 색상3분리 폐기 → 규격(mm) 변종 22종 승격 + 발주 재매칭.
-- 배경: 0414 단일SKU(spec 범위) → 0429 색상3분리(흑/백/도색). 실제 발주는 규격을 item_name '까치발 [Nmm]' 텍스트에만 보유,
--   전부 ACC-029-BK(id985)로 매칭됨(sm_bulk12_match.sql). 색상 실데이터 부재 → 사용자 결정: 색상값 아예 미설정(단일색), 규격만 개별품목.
-- 모델(0446 패턴): spec_group '까치발 규격' + 값22(150~2000mm) + 변종22(ACC-029-{size}, 985 상속). base=ACC-029 템플릿(is_active=0).
-- 재매칭: purchase_order_items '까치발 [Nmm]'(item_id IN 985,986,987 한정) → 규격SKU. 무규격 주문라인 '까치발' → base. 색상스텁 BK/WH/PT=is_active=0(0434 삭제금지·스텁유지).
-- idempotent: 전 INSERT NOT EXISTS 가드 · 재매칭 UPDATE는 이름+구id 한정(재실행시 0행).

-- 1) 규격그룹 '까치발 규격' + 값 22 (150~2000mm)
INSERT INTO spec_groups (name,unit,sort_order,is_active) SELECT '까치발 규격','mm',86,1 WHERE NOT EXISTS (SELECT 1 FROM spec_groups WHERE name='까치발 규격');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'150','150mm',150,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='150');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'200','200mm',200,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='200');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'250','250mm',250,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='250');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'300','300mm',300,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='300');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'350','350mm',350,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='350');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'400','400mm',400,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='400');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'500','500mm',500,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='500');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'600','600mm',600,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='600');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'700','700mm',700,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='700');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'800','800mm',800,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='800');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'900','900mm',900,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='900');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'1000','1000mm',1000,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='1000');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'1100','1100mm',1100,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='1100');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'1200','1200mm',1200,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='1200');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'1300','1300mm',1300,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='1300');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'1400','1400mm',1400,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='1400');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'1500','1500mm',1500,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='1500');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'1600','1600mm',1600,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='1600');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'1700','1700mm',1700,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='1700');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'1800','1800mm',1800,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='1800');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'1900','1900mm',1900,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='1900');
INSERT INTO spec_group_values (group_id,value_code,label,sort_order,is_active) SELECT (SELECT id FROM spec_groups WHERE name='까치발 규격'),'2000','2000mm',2000,1 WHERE NOT EXISTS (SELECT 1 FROM spec_group_values WHERE group_id=(SELECT id FROM spec_groups WHERE name='까치발 규격') AND value_code='2000');

-- 2) base 템플릿 ACC-029 '까치발' (985 상속, 변종 모품목, is_active=0)
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029','까치발',0,(SELECT id FROM spec_groups WHERE name='까치발 규격'),NULL,'150~2000mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029');

-- 3) 규격 변종 22 (ACC-029-{size}, 985 상속, 색상 텍스트 없음)
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-150','까치발 150mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'150','150mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-150');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-200','까치발 200mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'200','200mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-200');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-250','까치발 250mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'250','250mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-250');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-300','까치발 300mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'300','300mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-300');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-350','까치발 350mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'350','350mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-350');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-400','까치발 400mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'400','400mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-400');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-500','까치발 500mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'500','500mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-500');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-600','까치발 600mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'600','600mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-600');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-700','까치발 700mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'700','700mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-700');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-800','까치발 800mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'800','800mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-800');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-900','까치발 900mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'900','900mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-900');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-1000','까치발 1000mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'1000','1000mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-1000');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-1100','까치발 1100mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'1100','1100mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-1100');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-1200','까치발 1200mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'1200','1200mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-1200');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-1300','까치발 1300mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'1300','1300mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-1300');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-1400','까치발 1400mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'1400','1400mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-1400');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-1500','까치발 1500mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'1500','1500mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-1500');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-1600','까치발 1600mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'1600','1600mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-1600');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-1700','까치발 1700mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'1700','1700mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-1700');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-1800','까치발 1800mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'1800','1800mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-1800');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-1900','까치발 1900mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'1900','1900mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-1900');
INSERT INTO items (item_code,item_name,is_active,spec_group_id,spec_value,specification,item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description,created_at,updated_at)
SELECT 'ACC-029-2000','까치발 2000mm',1,(SELECT id FROM spec_groups WHERE name='까치발 규격'),'2000','2000mm', item_group,item_type,category_id,subcategory_id,category,sub_category,unit,base_price,sales_price,is_sales_item,is_purchase_item,pricing_method,pricing_profile,width_mm,group_sort,is_favorite,production_required,deduction_method,sheet_spec,waste_factor,stock_mode,description, datetime('now'), datetime('now')
FROM items WHERE item_code='ACC-029-BK' AND NOT EXISTS (SELECT 1 FROM items WHERE item_code='ACC-029-2000');

-- 4) 발주 재매칭: 까치발 [Nmm] → 규격SKU (구 색상id 985,986,987 한정 → 재실행 안전)
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-150'), updated_at=datetime('now') WHERE item_name='까치발 [150mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-200'), updated_at=datetime('now') WHERE item_name='까치발 [200mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-250'), updated_at=datetime('now') WHERE item_name='까치발 [250mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-300'), updated_at=datetime('now') WHERE item_name='까치발 [300mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-350'), updated_at=datetime('now') WHERE item_name='까치발 [350mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-400'), updated_at=datetime('now') WHERE item_name='까치발 [400mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-500'), updated_at=datetime('now') WHERE item_name='까치발 [500mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-600'), updated_at=datetime('now') WHERE item_name='까치발 [600mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-700'), updated_at=datetime('now') WHERE item_name='까치발 [700mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-800'), updated_at=datetime('now') WHERE item_name='까치발 [800mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-900'), updated_at=datetime('now') WHERE item_name='까치발 [900mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-1000'), updated_at=datetime('now') WHERE item_name='까치발 [1000mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-1100'), updated_at=datetime('now') WHERE item_name='까치발 [1100mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-1200'), updated_at=datetime('now') WHERE item_name='까치발 [1200mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-1300'), updated_at=datetime('now') WHERE item_name='까치발 [1300mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-1400'), updated_at=datetime('now') WHERE item_name='까치발 [1400mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-1500'), updated_at=datetime('now') WHERE item_name='까치발 [1500mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-1600'), updated_at=datetime('now') WHERE item_name='까치발 [1600mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-1700'), updated_at=datetime('now') WHERE item_name='까치발 [1700mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-1800'), updated_at=datetime('now') WHERE item_name='까치발 [1800mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-1900'), updated_at=datetime('now') WHERE item_name='까치발 [1900mm]' AND item_id IN (985,986,987);
UPDATE purchase_order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029-2000'), updated_at=datetime('now') WHERE item_name='까치발 [2000mm]' AND item_id IN (985,986,987);

-- 5) 무규격 주문라인 '까치발' → base ACC-029
UPDATE order_items SET item_id=(SELECT id FROM items WHERE item_code='ACC-029'), updated_at=datetime('now') WHERE item_name='까치발' AND item_id=985;

-- 6) 색상 스텁 비활성 (삭제금지·스텁 유지, 0434 규칙)
UPDATE items SET is_active=0, updated_at=datetime('now') WHERE item_code IN ('ACC-029-BK','ACC-029-WH','ACC-029-PT');
