UPDATE bank_transactions SET match_status='IGNORED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_reason='자기명의 이체/가수금' WHERE id=704 AND match_status='UNMATCHED';
UPDATE bank_transactions SET match_status='IGNORED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_reason='자기명의 이체/가수금' WHERE id=717 AND match_status='UNMATCHED';
UPDATE bank_transactions SET match_status='IGNORED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_reason='계좌간 자금이체' WHERE id=4131 AND match_status='UNMATCHED';
INSERT INTO payments (client_id, payment_date, amount, payment_method, reference_number, notes, created_by, entity_id) VALUES (3785, '2026-07-14', 10970000, '계좌이체', '2819', '[은행연동] 이정국새물광고 지역농축협', 9, 2);
UPDATE bank_transactions SET match_status='APPLIED', matched_client_id=3785, matched_link_mode='CREATED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_confidence=1.0, match_reason='입금 통장연결' WHERE id=2819 AND match_status='UNMATCHED';
UPDATE bank_transactions SET matched_payment_id=(SELECT id FROM payments WHERE reference_number='2819' AND entity_id=2 AND client_id=3785 ORDER BY id DESC LIMIT 1) WHERE id=2819;
UPDATE bank_transactions SET match_status='IGNORED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_reason='계좌간 자금이체' WHERE id=1094 AND match_status='UNMATCHED';
INSERT INTO payments (client_id, payment_date, amount, payment_method, reference_number, notes, created_by, entity_id) VALUES (314, '2026-07-09', 9400000, '계좌이체', '903', '[은행연동] 연현주(공감디자인) 국민은행', 9, 2);
UPDATE bank_transactions SET match_status='APPLIED', matched_client_id=314, matched_link_mode='CREATED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_confidence=1.0, match_reason='입금 통장연결' WHERE id=903 AND match_status='UNMATCHED';
UPDATE bank_transactions SET matched_payment_id=(SELECT id FROM payments WHERE reference_number='903' AND entity_id=2 AND client_id=314 ORDER BY id DESC LIMIT 1) WHERE id=903;
UPDATE bank_transactions SET match_status='IGNORED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_reason='계좌간 자금이체' WHERE id=722 AND match_status='UNMATCHED';
INSERT INTO payments (client_id, payment_date, amount, payment_method, reference_number, notes, created_by, entity_id) VALUES (2100, '2026-07-10', 4000000, '계좌이체', '1096', '[은행연동] (주)영기획 HanaCBS', 9, 2);
UPDATE bank_transactions SET match_status='APPLIED', matched_client_id=2100, matched_link_mode='CREATED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_confidence=1.0, match_reason='입금 통장연결' WHERE id=1096 AND match_status='UNMATCHED';
UPDATE bank_transactions SET matched_payment_id=(SELECT id FROM payments WHERE reference_number='1096' AND entity_id=2 AND client_id=2100 ORDER BY id DESC LIMIT 1) WHERE id=1096;
UPDATE bank_transactions SET match_status='IGNORED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_reason='계좌간 자금이체' WHERE id=769 AND match_status='UNMATCHED';
INSERT INTO payments (client_id, payment_date, amount, payment_method, reference_number, notes, created_by, entity_id) VALUES (329, '2026-07-10', 1050940, '계좌이체', '1075', '[은행연동] 광고기획팀 토스뱅크', 9, 2);
UPDATE bank_transactions SET match_status='APPLIED', matched_client_id=329, matched_link_mode='CREATED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_confidence=1.0, match_reason='입금 통장연결' WHERE id=1075 AND match_status='UNMATCHED';
UPDATE bank_transactions SET matched_payment_id=(SELECT id FROM payments WHERE reference_number='1075' AND entity_id=2 AND client_id=329 ORDER BY id DESC LIMIT 1) WHERE id=1075;
UPDATE bank_transactions SET match_status='IGNORED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_reason='계좌간 자금이체' WHERE id=929 AND match_status='UNMATCHED';
INSERT INTO payments (client_id, payment_date, amount, payment_method, reference_number, notes, created_by, entity_id) VALUES (1353, '2026-07-20', 870650, '계좌이체', '4920', '[은행연동] 김양숙 새마을금고중앙회(9826)', 9, 2);
UPDATE bank_transactions SET match_status='APPLIED', matched_client_id=1353, matched_link_mode='CREATED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_confidence=1.0, match_reason='입금 통장연결' WHERE id=4920 AND match_status='UNMATCHED';
UPDATE bank_transactions SET matched_payment_id=(SELECT id FROM payments WHERE reference_number='4920' AND entity_id=2 AND client_id=1353 ORDER BY id DESC LIMIT 1) WHERE id=4920;
UPDATE bank_transactions SET match_status='IGNORED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_reason='계좌간 자금이체' WHERE id=927 AND match_status='UNMATCHED';
INSERT INTO payments (client_id, payment_date, amount, payment_method, reference_number, notes, created_by, entity_id) VALUES (285, '2026-07-20', 712000, '계좌이체', '4921', '[은행연동] 김진영(경기애드컴) 지역농축협(4423)', 9, 2);
UPDATE bank_transactions SET match_status='APPLIED', matched_client_id=285, matched_link_mode='CREATED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_confidence=1.0, match_reason='입금 통장연결' WHERE id=4921 AND match_status='UNMATCHED';
UPDATE bank_transactions SET matched_payment_id=(SELECT id FROM payments WHERE reference_number='4921' AND entity_id=2 AND client_id=285 ORDER BY id DESC LIMIT 1) WHERE id=4921;
INSERT INTO payments (client_id, payment_date, amount, payment_method, reference_number, notes, created_by, entity_id) VALUES (1523, '2026-07-10', 652365, '계좌이체', '1936', '[은행연동] 임예슬 농협은행', 9, 2);
UPDATE bank_transactions SET match_status='APPLIED', matched_client_id=1523, matched_link_mode='CREATED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_confidence=1.0, match_reason='입금 통장연결' WHERE id=1936 AND match_status='UNMATCHED';
UPDATE bank_transactions SET matched_payment_id=(SELECT id FROM payments WHERE reference_number='1936' AND entity_id=2 AND client_id=1523 ORDER BY id DESC LIMIT 1) WHERE id=1936;
INSERT INTO payments (client_id, payment_date, amount, payment_method, reference_number, notes, created_by, entity_id) VALUES (2171, '2026-07-10', 598400, '계좌이체', '992', '[은행연동] (주)대운애드빌 신한은행(6664)', 9, 2);
UPDATE bank_transactions SET match_status='APPLIED', matched_client_id=2171, matched_link_mode='CREATED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_confidence=1.0, match_reason='입금 통장연결' WHERE id=992 AND match_status='UNMATCHED';
UPDATE bank_transactions SET matched_payment_id=(SELECT id FROM payments WHERE reference_number='992' AND entity_id=2 AND client_id=2171 ORDER BY id DESC LIMIT 1) WHERE id=992;
INSERT INTO payments (client_id, payment_date, amount, payment_method, reference_number, notes, created_by, entity_id) VALUES (1353, '2026-07-13', 572000, '계좌이체', '2754', '[은행연동] 김양숙 새마을금고중앙회(9826)', 9, 2);
UPDATE bank_transactions SET match_status='APPLIED', matched_client_id=1353, matched_link_mode='CREATED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_confidence=1.0, match_reason='입금 통장연결' WHERE id=2754 AND match_status='UNMATCHED';
UPDATE bank_transactions SET matched_payment_id=(SELECT id FROM payments WHERE reference_number='2754' AND entity_id=2 AND client_id=1353 ORDER BY id DESC LIMIT 1) WHERE id=2754;
UPDATE bank_transactions SET match_status='IGNORED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_reason='계좌간 자금이체' WHERE id=1091 AND match_status='UNMATCHED';
INSERT INTO payments (client_id, payment_date, amount, payment_method, reference_number, notes, created_by, entity_id) VALUES (2430, '2026-07-15', 416900, '계좌이체', '4129', '[은행연동] 이상진(포인트광고) 농협은행(4336)', 9, 2);
UPDATE bank_transactions SET match_status='APPLIED', matched_client_id=2430, matched_link_mode='CREATED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_confidence=1.0, match_reason='입금 통장연결' WHERE id=4129 AND match_status='UNMATCHED';
UPDATE bank_transactions SET matched_payment_id=(SELECT id FROM payments WHERE reference_number='4129' AND entity_id=2 AND client_id=2430 ORDER BY id DESC LIMIT 1) WHERE id=4129;
INSERT INTO payments (client_id, payment_date, amount, payment_method, reference_number, notes, created_by, entity_id) VALUES (2644, '2026-07-10', 330000, '계좌이체', '1089', '[은행연동] 서해성 대체', 9, 2);
UPDATE bank_transactions SET match_status='APPLIED', matched_client_id=2644, matched_link_mode='CREATED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_confidence=1.0, match_reason='입금 통장연결' WHERE id=1089 AND match_status='UNMATCHED';
UPDATE bank_transactions SET matched_payment_id=(SELECT id FROM payments WHERE reference_number='1089' AND entity_id=2 AND client_id=2644 ORDER BY id DESC LIMIT 1) WHERE id=1089;
UPDATE bank_transactions SET match_status='IGNORED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_reason='와우프레스(명함 매입처) 선입금 관련 — AR 아님' WHERE id=767 AND match_status='UNMATCHED';
UPDATE bank_transactions SET match_status='IGNORED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_reason='기타수입(보험해약금)' WHERE id=2923 AND match_status='UNMATCHED';
UPDATE bank_transactions SET match_status='IGNORED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_reason='자기명의 이체/가수금' WHERE id=905 AND match_status='UNMATCHED';
UPDATE bank_transactions SET match_status='IGNORED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_reason='공장 임대인(신경옥) 전기세 잔여분 정산 — 수금 아님' WHERE id=3020 AND match_status='UNMATCHED';
UPDATE bank_transactions SET match_status='IGNORED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_reason='기타수입(은행이자)' WHERE id=2849 AND match_status='UNMATCHED';
UPDATE bank_transactions SET match_status='IGNORED', matched_by=9, matched_at=CURRENT_TIMESTAMP, match_reason='기타수입(은행이자)' WHERE id=3219 AND match_status='UNMATCHED';
