// scripts/build-assets.mjs
// 클라이언트 JS 정적 에셋 빌드 (P0 파일럿: shell.js만)
// 설계: docs/design/static-assets-migration.md
//
// 동작:
//   1) src/scripts/layout/shell.js → esbuild minify
//   2) content hash(sha256 8자) → dist/static/shell.<hash>.js 기록
//   3) src/generated/asset-manifest.ts 생성(커밋 대상 — tsc 단독 통과용)
//   4) dist/_routes.json  : /static/* 를 워커 라우팅에서 제외 (CF Pages 정적 서빙)
//   5) dist/_headers      : /static/* 불변 캐시 헤더
//
// vite build 이전에 실행. (hono 플러그인은 emptyOutDir:false + 기존 _routes.json 보존)
//   package.json: "build": "npm run build:assets && vite build"

import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { transform } from 'esbuild'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const p = (...s) => resolve(ROOT, ...s)

// 외부화 대상 (파일럿: shell 1개. P1~P3에서 항목 추가)
const ASSETS = [
  { key: 'shell', src: 'src/scripts/layout/shell.js' },
]

const STATIC_DIR = p('dist', 'static')
const GEN_DIR = p('src', 'generated')

function ensureDir(d) { mkdirSync(d, { recursive: true }) }

// 안전한 minify: 전역 식별자(window 노출 함수 등)는 보존, 공백/구문만 축소
async function minify(code) {
  const out = await transform(code, {
    loader: 'js',
    minifyWhitespace: true,
    minifySyntax: true,
    minifyIdentifiers: false, // 전역 함수명 보존 (onclick/타 인라인 스크립트에서 호출)
    legalComments: 'none',
  })
  return out.code
}

async function build() {
  ensureDir(STATIC_DIR)
  ensureDir(GEN_DIR)

  const manifest = {}

  for (const { key, src } of ASSETS) {
    const raw = readFileSync(p(src), 'utf8')
    const min = await minify(raw)
    const hash = createHash('sha256').update(min).digest('hex').slice(0, 8)
    const fileName = `${key}.${hash}.js`

    // 동일 key의 이전 해시 파일 정리 (emptyOutDir:false 라 누적 방지)
    if (existsSync(STATIC_DIR)) {
      for (const f of readdirSync(STATIC_DIR)) {
        if (f.startsWith(`${key}.`) && f.endsWith('.js') && f !== fileName) {
          rmSync(resolve(STATIC_DIR, f))
        }
      }
    }

    writeFileSync(resolve(STATIC_DIR, fileName), min)
    manifest[key] = fileName
    console.log(`[build-assets] ${src} → dist/static/${fileName}  (${raw.length}B → ${min.length}B)`)
  }

  // 생성 manifest 모듈 (커밋 대상)
  const ts =
    '// AUTO-GENERATED by scripts/build-assets.mjs — do not edit.\n' +
    'export const ASSET_MANIFEST = ' + JSON.stringify(manifest, null, 2) + ' as const\n'
  writeFileSync(p('src', 'generated', 'asset-manifest.ts'), ts)

  // _routes.json: /static/* 를 워커에서 제외 (플러그인이 기존 파일 있으면 보존)
  writeFileSync(
    p('dist', '_routes.json'),
    JSON.stringify({ version: 1, include: ['/*'], exclude: ['/static/*'] })
  )

  // _headers: /static/* 불변 캐시 + Content-Type 명시
  // ⚠️ Content-Type 필수: CF Pages 자동 MIME 감지가 빈값('')으로 서빙되는 경우가 있어
  //    (asset blob 재사용 시) 브라우저가 'MIME type not executable'로 실행 거부 → shell.js 사망.
  //    명시 헤더는 edge에서 요청 시 적용되므로 blob 재업로드 여부와 무관하게 보장됨.
  //    현재 /static/* = JS 에셋만(파일럿+P1~P3 클라 스크립트). 비-JS 추가 시 확장자별 규칙 분리 필요.
  writeFileSync(
    p('dist', '_headers'),
    '# AUTO-GENERATED by scripts/build-assets.mjs\n' +
    '/static/*\n' +
    '  Content-Type: text/javascript; charset=utf-8\n' +
    '  Cache-Control: public, max-age=31536000, immutable\n'
  )

  console.log('[build-assets] manifest:', JSON.stringify(manifest))
}

build().catch((e) => { console.error(e); process.exit(1) })
