// scripts/build-assets.mjs
// CF Pages 정적 라우팅 파일(_routes.json / _headers) 생성.
//
// #383: shell.js 외부화 파일럿(9dd09cd)은 CF Pages 자동빌드 MIME 거부로 prod 2회 다운 →
//   24bb493에서 layout.ts `?raw` 인라인 복귀로 폐기. 그 잔재(dead dist/static/shell.<hash>.js 방출 +
//   미사용 src/generated/asset-manifest.ts = 재외부화 오배선 트랩)를 제거.
//   ⚠️ 라우팅 파일(_routes.json/_headers)은 현재 prod와 byte-identical 유지 → 워커 라우팅 영향 0.
//
// vite build 이전 실행. (hono 플러그인이 기존 _routes.json을 보존)
//   package.json: "build": "npm run build:assets && vite build"

import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const p = (...s) => resolve(ROOT, ...s)

function build() {
  mkdirSync(p('dist'), { recursive: true })

  // _routes.json: /static/* 를 워커 라우팅에서 제외 (CF Pages 정적 서빙). 현재 prod와 동일 유지.
  writeFileSync(
    p('dist', '_routes.json'),
    JSON.stringify({ version: 1, include: ['/*'], exclude: ['/static/*'] })
  )

  // _headers: /static/* 불변 캐시 + Content-Type 명시. 현재 prod와 동일 유지.
  writeFileSync(
    p('dist', '_headers'),
    '# AUTO-GENERATED by scripts/build-assets.mjs\n' +
    '/static/*\n' +
    '  Content-Type: text/javascript; charset=utf-8\n' +
    '  Cache-Control: public, max-age=31536000, immutable\n'
  )

  console.log('[build-assets] _routes.json + _headers 생성 (shell 외부화 폐기 — layout.ts ?raw 인라인)')
}

build()
